---
title: "pud_delay_trial"
author: "Dianovics Dominik"
date: "2023-11-12"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(jsonlite)
library(future.apply)
library(progress)
library(grDevices)
library(papaja)
```

```{r data import}

data_link <- "pubmed_medline_articles_partial.json"

jr_link <- "scimagojr 2022.csv"

jr2022 <- read.csv(jr_link)

jr2022 <- jr2022 |> 
  select(-Publisher, -Region, -Sourceid, -Cites...Doc...2years., -Total.Docs., -Total.Docs...3years., -Total.Refs., -Ref....Doc., -Citable.Docs...3years.)
```

```{r data import_timed}
track_execution_time <- function(chunk_name) {
  start_time <- Sys.time()
  
  
  end_time <- Sys.time()
  
  elapsed_time <- end_time - start_time
  cat(paste("Chunk", chunk_name, "took", round(as.numeric(elapsed_time), 2), "seconds to execute.\n"))
}

track_execution_time("data import_timed")

plan(multicore(workers = 4))
json <- fromJSON(data_link)
```

```{r}

json$year <- sub(".*(\\d{4}).*", "\\1", json$pubdate)

```

```{r Create Dates}

json$received <- as.Date(json$history$received, format = "%Y-%m-%d")

json$revised <- as.Date(json$history$revised, format = "%Y-%m-%d")

json$accepted <- as.Date(json$history$accepted, format = "%Y-%m-%d")

json$pubmed <- as.Date(json$history$pubmed, format = "%Y-%m-%d")


```

```{r}

pub_types <- json %>%
  group_by(publication_types) %>%
  summarize(counts = n()) %>%
  mutate(proportion = counts / sum(counts))


```

```{r Publication type filter}
filters <- c("D003160:Comparative Study", "D016428:Journal Article", "D002363:Case Reports", "D017418:Meta-Analysis")

filtered_publication_type <- str_detect(json$publication_types, paste(filters, collapse = "|"))

filtered_json <- json[filtered_publication_type, ]

print(filtered_json)

```

```{r Create delays}

filtered_json = filtered_json |>
  mutate(
    publication_delay = pubmed - accepted,
    acceptance_delay = accepted - received
  )

```

```{r}

filtered_json$issn <- gsub("-", "", filtered_json$issn_linking)

filtered_json$issn <- trimws(filtered_json$issn)



jr2022$issn = jr2022$Issn

jr2022 <- jr2022[, !(names(jr2022) %in% c("Issn"))]

jr2022_sep <- jr2022 %>%
  separate(issn, into = c("issn1", "issn2"), sep = ", ", remove = FALSE)

jr2022_sep$issn1 <- trimws(jr2022_sep$issn1)

jr2022_sep$issn2 <- trimws(jr2022_sep$issn2)


```

```{r Unimportant journals filter}
merged_delay <- filtered_json %>%
  left_join(jr2022_sep, by = c("issn" = "issn1")) %>%
  left_join(jr2022_sep, by = c("issn" = "issn2")) %>%
  mutate(issn_matched = coalesce(issn1, issn2)) |> 
  select(title:Areas_5.x)

merged_delay |> 
  filter(is.na(SJR.x)) |> 
  group_by(issn) |> 
  count(issn, sort = TRUE)


not_missing <- merged_delay |> 
  filter(!is.na(SJR.x))
```

```{r Invalid delays filter}
everything_filtered <- not_missing |> 
  filter(publication_delay > 1 & acceptance_delay > 1)



```

```{r}
#Article date needed
```


```{r Covid pattern}
covid_pattern <- c("COVID", "covid", "Covid", "COVID-19", "coronavirus", "SARS", "2019-nCoV")

covid_articles <- str_detect(everything_filtered$title, paste(covid_pattern, collapse = "|")) |
          str_detect(everything_filtered$keywords, paste(covid_pattern, collapse = "|"))

covid_articles_df <- everything_filtered[covid_articles, ]

covid_articles_df <- covid_articles_df |> 
  filter(year > 2019)

```

```{r Replication pattern}
replication_pattern <- c("replication study", "Replication Study", "replication report", "registered replication report", "Registered replication report", "replication of", "Replication of", "Registered Replication Report")

replication_articles <- str_detect(everything_filtered$title, paste(replication_pattern, collapse = "|")) |
          str_detect(everything_filtered$keywords, paste(replication_pattern, collapse = "|"))

replication_articles_df <- everything_filtered[replication_articles, ]
```

```{r Font}
windowsFonts(Times = windowsFont("Times New Roman"))
```


```{r Acceptance plot}
acceptance_plot <- ggplot(everything_filtered, aes(x = pubdate, y = acceptance_delay, group = 1)) +
  geom_smooth(method = "loess", se = TRUE, span = 1, color = "black", linewidth = 1.2) +
  geom_point(alpha = 1/ 20) +
  labs(y = "Acceptance delay (days)", x = "Year") +
  theme_apa() +
  theme(axis.text.x = element_text(size = 16, family = "Times", hjust = 1),
        axis.text.y = element_text(size = 16, family = "Times"),
        axis.title = element_text(size = 22, family = "Times")) +
  ylim(0, 200)



print(acceptance_plot)
  
file.path("acceptance_plot.png") |> 
  ggsave(acceptance_plot, width = 7, height = 7, scale = 0.9)
```

```{r Publication plot}
publication_plot <- ggplot(everything_filtered, aes(x = pubdate, y = publication_delay, group = 1)) +
  geom_smooth(method = "loess", se = TRUE, span = 1, color = "black", linewidth = 1.2) +
  geom_point(alpha = 1/ 20) +
  labs(y = "Publication delay (days)", x = "Year") +
  theme_apa() +
  theme(axis.text.x = element_text(size = 16, family = "Times", hjust = 1), 
        axis.text.y = element_text(size = 16, family = "Times"),
        axis.title = element_text(size = 22, family = "Times")) +
  ylim(0, 100)


print(publication_plot)
  
file.path("publication_plot.png") |> 
  ggsave(publication_plot, width = 8, height = 8, scale = 0.9)
```

```{r Covid acceptance plot}

covid_acceptance_plot <- ggplot(everything_filtered, aes(x = pubdate, y = acceptance_delay, group = 1)) +
  geom_smooth(method = "loess", se = TRUE, span = 1, color = "black", linewidth = 1.2) +
  geom_point(data = covid_articles_df, aes(x = year, y = acceptance_delay), color = "red") +
  geom_smooth(data = covid_articles_df, method = "loess", se = TRUE, span = 1, color = "red") +
  labs(y = "Acceptance delay (days)", x = "Year") +
  theme_apa() +
  theme(axis.text.x = element_text(size = 16, family = "Times", hjust = 1), 
        axis.text.y = element_text(size = 16, family = "Times"),
        axis.title = element_text(size = 22, family = "Times")) +
  ylim(0, 200)

print(covid_acceptance_plot)

  
file.path("covid_acceptance_plot.png") |> 
  ggsave(acceptance_plot, width = 8, height = 8, scale = 0.9)
```

```{r Covid publication plot}
covid_publication_plot <- ggplot(everything_filtered, aes(x = pubdate, y = publication_delay, group = 1)) +
  geom_smooth(method = "loess", se = TRUE, span = 1, color = "black", linewidth = 1.2) +
  geom_point(data = covid_articles_df, aes(x = year, y = publication_delay), color = "red") +
  geom_smooth(data = covid_articles_df, method = "loess", se = TRUE, span = 1, color = "red") +
  labs(y = "Publication delay (days)", x = "Year") +
  theme_apa() +
  theme(axis.text.x = element_text(size = 16, family = "Times", hjust = 1), 
        axis.text.y = element_text(size = 16, family = "Times"),
        axis.title = element_text(size = 22, family = "Times")) +
  ylim(0, 100)

print(covid_publication_plot)

  
file.path("covid_publication_plot.png") |> 
  ggsave(acceptance_plot, width = 8, height = 8, scale = 0.9)
```

```{r Discipline grouping}
unique_disciplines <- everything_filtered %>%
  select(starts_with("Areas_")) %>%
  unlist() %>%
  na.omit() %>%
  unique()

print(unique_disciplines)


discipline_types <- everything_filtered %>%
  pivot_longer(cols = starts_with("Areas_"), names_to = "Area", values_to = "discipline") %>%
  mutate(discipline = str_trim(discipline)) %>%
  group_by(discipline) %>%
  summarize(counts = n()) %>%
  arrange(desc(counts)) %>%
  mutate(area_counts = rowSums(across(starts_with("Areas_"), ~ !is.na(.)))) %>%
  select(discipline, counts)


print(discipline_types[1])



discipline_types$discipline_1 <- case_when(
  discipline_types$discipline %in% c("Medicine", "Pharmacology, Toxicology and Pharmaceutics", "Health Professions", "Nursing", "Dentistry", "Veterinary") ~ "Medical Sciences",
  discipline_types$discipline %in% c("Biochemistry", "Biochemistry, Genetics and Molecular Biology", "Agricultural and Biological Sciences", "Immunology and Microbiology", "Environmental Science", "Neuroscience") ~ "Life Sciences",
  discipline_types$discipline %in% c("Physics and Astronomy", "Chemistry", "Materials Science", "Earth and Planetary Sciences") ~ "Physical Sciences",
  discipline_types$discipline %in% c("Engineering", "Chemical Engineering", "Energy", "Computer Science") ~ "Engineering and Technology",
  discipline_types$discipline %in% c("Social Sciences", "Arts and Humanities", "Business, Management and Accounting", "Decision Sciences", "Economics, Econometrics and Finance", "Psychology") ~ "Social Sciences",
  discipline_types$discipline %in% c("Mathematics", "Computer Science") ~ "Mathematics and Computational Sciences",
  TRUE ~ "Other"
)
```

```{r}
everything_filtered$Areas_2.x <- everything_filtered$Areas_2.x %>% trimws()
everything_filtered$Areas_3.x <- everything_filtered$Areas_3.x %>% trimws()
everything_filtered$Areas_4.x <- everything_filtered$Areas_4.x %>% trimws()
everything_filtered$Areas_5.x <- everything_filtered$Areas_5.x %>% trimws()


everything_filtered <- everything_filtered %>%
  mutate(
    discipline1 = case_when(
      Areas_1.x %in% c("Medicine", "Pharmacology, Toxicology and Pharmaceutics", "Health Professions", "Nursing", "Dentistry", "Veterinary") ~ "Medical Sciences",
      Areas_1.x %in% c("Biochemistry", "Biochemistry, Genetics and Molecular Biology", "Agricultural and Biological Sciences", "Immunology and Microbiology", "Environmental Science", "Neuroscience") ~ "Life Sciences",
      Areas_1.x %in% c("Physics and Astronomy", "Chemistry", "Materials Science", "Earth and Planetary Sciences") ~ "Physical Sciences",
      Areas_1.x %in% c("Engineering", "Chemical Engineering", "Energy", "Computer Science") ~ "Engineering and Technology",
      Areas_1.x %in% c("Social Sciences", "Arts and Humanities", "Business, Management and Accounting", "Decision Sciences", "Economics, Econometrics and Finance", "Psychology") ~ "Social Sciences",
      Areas_1.x %in% c("Mathematics", "Computer Science") ~ "Mathematics and Computational Sciences",
      TRUE ~ "Other"
    ),
     discipline2 = case_when(
      Areas_2.x %in% c("Medicine", "Pharmacology, Toxicology and Pharmaceutics", "Health Professions", "Nursing", "Dentistry", "Veterinary") ~ "Medical Sciences",
      Areas_2.x %in% c("Biochemistry", "Biochemistry, Genetics and Molecular Biology", "Agricultural and Biological Sciences", "Immunology and Microbiology", "Environmental Science", "Neuroscience") ~ "Life Sciences",
      Areas_2.x %in% c("Physics and Astronomy", "Chemistry", "Materials Science", "Earth and Planetary Sciences") ~ "Physical Sciences",
      Areas_2.x %in% c("Engineering", "Chemical Engineering", "Energy", "Computer Science") ~ "Engineering and Technology",
      Areas_2.x %in% c("Social Sciences", "Arts and Humanities", "Business, Management and Accounting", "Decision Sciences", "Economics, Econometrics and Finance", "Psychology") ~ "Social Sciences",
      Areas_2.x %in% c("Mathematics", "Computer Science") ~ "Mathematics and Computational Sciences",
      TRUE ~ "Other"
     ),
     discipline3 = case_when(
      Areas_3.x %in% c("Medicine", "Pharmacology, Toxicology and Pharmaceutics", "Health Professions", "Nursing", "Dentistry", "Veterinary") ~ "Medical Sciences",
      Areas_3.x %in% c("Biochemistry", "Biochemistry, Genetics and Molecular Biology", "Agricultural and Biological Sciences", "Immunology and Microbiology", "Environmental Science", "Neuroscience") ~ "Life Sciences",
      Areas_3.x %in% c("Physics and Astronomy", "Chemistry", "Materials Science", "Earth and Planetary Sciences") ~ "Physical Sciences",
      Areas_3.x %in% c("Engineering", "Chemical Engineering", "Energy", "Computer Science") ~ "Engineering and Technology",
      Areas_3.x %in% c("Social Sciences", "Arts and Humanities", "Business, Management and Accounting", "Decision Sciences", "Economics, Econometrics and Finance", "Psychology") ~ "Social Sciences",
      Areas_3.x %in% c("Mathematics", "Computer Science") ~ "Mathematics and Computational Sciences",
      TRUE ~ "Other"
     ),
     discipline4 = case_when(
      Areas_4.x %in% c("Medicine", "Pharmacology, Toxicology and Pharmaceutics", "Health Professions", "Nursing", "Dentistry", "Veterinary") ~ "Medical Sciences",
      Areas_4.x %in% c("Biochemistry", "Biochemistry, Genetics and Molecular Biology", "Agricultural and Biological Sciences", "Immunology and Microbiology", "Environmental Science", "Neuroscience") ~ "Life Sciences",
      Areas_4.x %in% c("Physics and Astronomy", "Chemistry", "Materials Science", "Earth and Planetary Sciences") ~ "Physical Sciences",
      Areas_4.x %in% c("Engineering", "Chemical Engineering", "Energy", "Computer Science") ~ "Engineering and Technology",
      Areas_4.x %in% c("Social Sciences", "Arts and Humanities", "Business, Management and Accounting", "Decision Sciences", "Economics, Econometrics and Finance", "Psychology") ~ "Social Sciences",
      Areas_4.x %in% c("Mathematics", "Computer Science") ~ "Mathematics and Computational Sciences",
      TRUE ~ "Other"
     ),
     discipline5 = case_when(
      Areas_5.x %in% c("Medicine", "Pharmacology, Toxicology and Pharmaceutics", "Health Professions", "Nursing", "Dentistry", "Veterinary") ~ "Medical Sciences",
      Areas_5.x %in% c("Biochemistry", "Biochemistry, Genetics and Molecular Biology", "Agricultural and Biological Sciences", "Immunology and Microbiology", "Environmental Science", "Neuroscience") ~ "Life Sciences",
      Areas_5.x %in% c("Physics and Astronomy", "Chemistry", "Materials Science", "Earth and Planetary Sciences") ~ "Physical Sciences",
      Areas_5.x %in% c("Engineering", "Chemical Engineering", "Energy", "Computer Science") ~ "Engineering and Technology",
      Areas_5.x %in% c("Social Sciences", "Arts and Humanities", "Business, Management and Accounting", "Decision Sciences", "Economics, Econometrics and Finance", "Psychology") ~ "Social Sciences",
      Areas_5.x %in% c("Mathematics", "Computer Science") ~ "Mathematics and Computational Sciences",
      TRUE ~ "Other"
     ) 
  ) |> 
  select(-Areas_1.x, -Areas_2.x, -Areas_3.x, -Areas_4.x, -Areas_5.x)


```


```{r}
medical_science_articles <- everything_filtered |> 
  filter(discipline1 == "Medical Sciences" | discipline2 == "Medical Sciences" | discipline3 == "Medical Sciences" | discipline4 == "Medical Sciences" | discipline5 == "Medical Sciences") |>
  mutate(
    discipline = "medical_science"
  ) |> 
  select(-discipline1, -discipline2, -discipline3, -discipline4, -discipline5, acceptance_delay, publication_delay, year, pubdate, discipline)


life_science_articles <- everything_filtered |>
  filter(discipline1 == "Life Sciences" | discipline2 == "Life Sciences" | discipline3 == "Life Sciences" | discipline4 == "Life Sciences" | discipline5 == "Life Sciences") |> 
  mutate(
    discipline = "life_science"
  ) |> 
  select(-discipline1, -discipline2, -discipline3, -discipline4, -discipline5, acceptance_delay, publication_delay, year, pubdate, discipline)

physical_science_articles <- everything_filtered |>
  filter(discipline1 == "Physical Sciences" | discipline2 == "Physical Sciences" | discipline3 == "Physical Sciences" | discipline4 == "Physical Sciences" | discipline5 == "Physical Sciences") |> 
  mutate(
    discipline = "physical_science"
  ) |> 
  select(-discipline1, -discipline2, -discipline3, -discipline4, -discipline5, acceptance_delay, publication_delay, year, pubdate, discipline)

engineering_and_technology_articles <- everything_filtered |>
  filter(discipline1 == "Engineering and Technology" | discipline2 == "Engineering and Technology" | discipline3 == "Engineering and Technology" | discipline4 == "Engineering and Technology" | discipline5 == "Engineering and Technology") |> 
  mutate(
    discipline = "engineering_and_technology"
  ) |> 
  select(-discipline1, -discipline2, -discipline3, -discipline4, -discipline5, acceptance_delay, publication_delay, year, pubdate, discipline)

social_science_articles <- everything_filtered |>
  filter(discipline1 == "Social Sciences" | discipline2 == "Social Sciences" | discipline3 == "Social Sciences" | discipline4 == "Social Sciences" | discipline5 == "Social Sciences") |> 
  mutate(
    discipline = "social_science"
  ) |> 
  select(-discipline1, -discipline2, -discipline3, -discipline4, -discipline5, acceptance_delay, publication_delay, year, pubdate, discipline)



discipline_combined <- rbind(medical_science_articles, life_science_articles, physical_science_articles, engineering_and_technology_articles, social_science_articles)
  

plot <- discipline_combined |> 
  ggplot(aes(x = pubdate, y = acceptance_delay, group = discipline, color = discipline)) +
  geom_smooth(se = FALSE)


print(plot)


```

```{r}
```

